# Generated by Django 4.2.4 on 2023-08-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_blog_priority_alter_education_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearsOfExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.IntegerField(default=6)),
            ],
        ),
    ]
