# Generated by Django 4.2.4 on 2023-08-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='portfolio/media/placeholder.png', upload_to='portfolio/media/'),
        ),
    ]
