# Generated by Django 4.2.4 on 2023-08-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_alter_project_icon_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='collapse',
            field=models.CharField(default='collapse in', max_length=100),
        ),
        migrations.AddField(
            model_name='education',
            name='header_class',
            field=models.CharField(default='', max_length=100),
        ),
    ]
