# Generated by Django 4.2.4 on 2023-08-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_education_collapse_education_header_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='header_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
