# Generated by Django 4.2.4 on 2023-08-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_alter_education_header_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='collapse_count',
            field=models.CharField(default='collapseOne', max_length=100),
            preserve_default=False,
        ),
    ]
